################################################################################
# 自动生成的文件。不要编辑！
################################################################################

define INFO_NOT_CONFIGURED
*************************************************************
The active configuration requires additional settings.
Please see the documentation task:
"Configuring an external GCC Toolchain".
*************************************************************
endef

clean:
info:
	$(info $(INFO_NOT_CONFIGURED))
all: info
	$(error The selected build configuration is not complete.))